config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
	mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
	 get '/user_dashboard', to: 'userdashboard#index'
  devise_for :users
	scope "/admin" do
	  resources :users
	end
  root to: "home#index"
end

app/models/application_record.rb
# frozen_string_literal: true

# application_record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

# models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  scope :all_non_admin_users, -> { where.not role: 'admin' }

  after_initialize :set_default_role, if: :new_record?
  after_create :send_reset_password_instructions
  enum role: %I[admin user]

  def friendly_password
    password_length = 6
    Devise.friendly_token.first(password_length)
  end

  def set_default_role
    self.role ||= 1
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def authorize_admin
    return if current_user.admin?

    render file: "#{Rails.root}/public/404", status: :not_found
  end

  def after_sign_in_path_for(resource)
  	return if current_user.admin?

  	user_dashboard_path
	end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
end

app/controllers/userdashboard_controller.rb
class UserdashboardController < ApplicationController
	def index
	end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# controllers/users_controller
class UsersController < ApplicationController
  before_action :authenticate_user!, :authorize_admin
  before_action :set_user, only: %i[show edit update destroy]
  before_action :initialize_user, only: %i[create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all_non_admin_users

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    respond_to do |format|
      if @user.save
        format.html do
          redirect_to @user,
                      notice: 'User account successfully created.
                               A password reset email has been sent
                               to the user.'
        end
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def initialize_user
    @user = User.new(user_params)
    @user.password = @user.friendly_password
    @user.password_confirmation = @user.password
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user)
          .permit(:email, :password,
                  :password_confirmation, :full_name,
                  :phone_number, :company_name,
                  :company_address)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# helpers/application_helper
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# helpers/home_helper
module HomeHelper
end

app/helpers/userdashboard_helper.rb
module UserdashboardHelper
end

app/views/home/index.html.erb
<div class="container my-4">
  <div class="border border-light p-3 mb-4">
    <div class="d-flex align-items-center justify-content-center">
      <h3>Welcome To Take Home Exercise</h3>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TakeHomeExcercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'shared/header'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_devise_messages.html.erb
<% flash.each do |key, value| %>
  <div class ="alert alert-<%=key == 'notice' ? 'success' : 'danger' %>">
    <% if value.is_a?(Array)%>
      <%value.each do |v|%>
          <li><%=v%></li>
      <%end%>
      <%else%>
        <li><%=value%></li>
      <%end%>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <ul class="alert alert-danger">
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <script type="text/javascript">
          toastr.error('<%= message %>')
        </script>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom box-shadow">
    <a href="<%=root_path%>" class='navbar-brand py-2'>
      Take Home
    </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in?%>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%=link_to 'Accounts', users_path, class: "p-2 text-dark nav-link"%>
        </li>
      </ul>
    <%end%>
    <div class="navbar-nav ml-auto action-buttons">
      <% unless user_signed_in?%>
        <%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary"%>
      <%end%>
      <% if user_signed_in?%>
        <ul class="nav navbar-nav justify-content-end">
          <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email%>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to 'Logout', destroy_user_session_path, method: :delete,
                  class: 'p-2 text-dark dropdown-item'%>
            </div>
          </li>
        </ul>
      <%end%>
    </div>
  </div>
</nav>

app/views/shared/_messages.html.erb
<% if !object.nil? &&  object.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <%= content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String) %>
      <% end %>
    </ul>
  </div>
<% end %>

<% if flash.notice.present? %>
  <div class="alert alert-success" role="alert">
    <p><%=flash.notice%></p>
  </div>
<%end%>

app/views/userdashboard/index.html.erb
<div class="container my-4">
  <div class="border border-light p-3 mb-4">
    <div class="d-flex align-items-center justify-content-center">
      <h3>welcome to your dashboard</h3>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="container">
  <div class="card mt-2">
    <div class="card-header bg-dark text-white">
      Account
    </div>
    <div class="card-body">
      <%= form_with(model: @user, local: true) do |form| %>
         <%= render 'shared/messages', object: @user %>
        <%= render "shared/error_messages", resource: @user %>
        <div class="form-group">
          <%= form.label :full_name %>
          <%= form.text_field :full_name, class: "form-control form-control-sm" %>
        </div>
        <div class="form-group">
          <%= form.label :email %>
          <%= form.email_field :email, class: "form-control form-control-sm" %>
        </div>

        <div class="form-group">
          <%= form.label :phone_number %>
          <%= form.text_field :phone_number, class: "form-control form-control-sm" %>
        </div>

        <div class="form-group">
          <%= form.label :company_name %>
          <%= form.text_field :company_name, class: "form-control form-control-sm" %>
        </div>

        <div class="form-group">
          <%= form.label :company_address %>
          <%= form.text_field :company_address, class: "form-control form-control-sm" %>
        </div>


        <div class="form-group d-flex justify-content-between mt-5">
          <%= form.submit "Submit", class: 'btn btn-sm btn-success'%>
          <%= link_to 'Back', users_path, class: 'btn btn-sm btn-warning'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div class="container">
  <div class="card mt-2">
    <div class="card-header bg-dark text-white">
      Accounts
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <p id="notice"><%= notice %></p>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>S. No</th>
              <th>Full Name</th>
							<th>Email</th>
							<th>Phone Number</th>
							<th>Company Name</th>
							<th>Company Address</th>
              <th colspan="3">Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each_with_index do |user, index| %>
              <tr>
                <td><%=index+1%></td>
                	<td><%= user.full_name %></td>
									<td><%= user.email %></td>
									<td><%= user.phone_number %></td>
									<td><%= user.company_name %></td>
									<td><%= user.company_address %></td>
									<td><%= link_to 'Show', user%></td>
									<td><%= link_to "Edit", edit_user_path(user) %></td>
									<td><%= link_to "Delete", user, :method => :delete, :confirm => "Are you sure?" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer">
      <div class="d-flex justify-content-between">
        <div>
          <%= link_to "New User", new_user_path, class: "btn btn-sm btn-info"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= render 'form' %>